/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTallyRouteImport } from './routes/_app.tally'
import { Route as AppOtRouteImport } from './routes/_app.ot'
import { Route as AppNursingRouteImport } from './routes/_app.nursing'
import { Route as AppNabhRouteImport } from './routes/_app.nabh'
import { Route as AppMrdRouteImport } from './routes/_app.mrd'
import { Route as AppRadiologyLabRouteImport } from './routes/_app.radiology-lab'
import { Route as AppPathologyLabRouteImport } from './routes/_app.pathology-lab'
import { Route as AppInvestigationsRouteImport } from './routes/_app.investigations'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdministrationRouteImport } from './routes/_app.administration'
import { Route as AppOpdPatientRegistrationRouteImport } from './routes/_app.opd.patient-registration'
import { Route as AppOpdPatientQueueRouteImport } from './routes/_app.opd.patient-queue'
import { Route as AppOpdMedicalRecordRouteImport } from './routes/_app.opd.medical-record'
import { Route as AppOpdBillSettlementRouteImport } from './routes/_app.opd.bill-settlement'
import { Route as AppOpdBillRefundRouteImport } from './routes/_app.opd.bill-refund'
import { Route as AppOpdBillListRouteImport } from './routes/_app.opd.bill-list'
import { Route as AppOpdBillConcessionRouteImport } from './routes/_app.opd.bill-concession'
import { Route as AppOpdBillRouteImport } from './routes/_app.opd.bill'
import { Route as AppOpdAppointmentsRouteImport } from './routes/_app.opd.appointments'
import { Route as AppIpdTokenDisplayRouteImport } from './routes/_app.ipd.token-display'
import { Route as AppIpdEreRouteImport } from './routes/_app.ipd.ere'
import { Route as AppIpdChargeRouteImport } from './routes/_app.ipd.charge'
import { Route as AppIpdAdmissionListRouteImport } from './routes/_app.ipd.admission-list'
import { Route as AppIpdAdmissionRouteImport } from './routes/_app.ipd.admission'
import { Route as AppIpdWardPrivateRouteImport } from './routes/_app.ipd.ward.private'
import { Route as AppIpdWardIcuRouteImport } from './routes/_app.ipd.ward.icu'
import { Route as AppIpdWardGeneralRouteImport } from './routes/_app.ipd.ward.general'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} )
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} )
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} )
const AppTallyRoute = AppTallyRouteImport.update({
  id: '/tally',
  path: '/tally',
  getParentRoute: () => AppRoute,
} )
const AppOtRoute = AppOtRouteImport.update({
  id: '/ot',
  path: '/ot',
  getParentRoute: () => AppRoute,
} )
const AppNursingRoute = AppNursingRouteImport.update({
  id: '/nursing',
  path: '/nursing',
  getParentRoute: () => AppRoute,
} )
const AppNabhRoute = AppNabhRouteImport.update({
  id: '/nabh',
  path: '/nabh',
  getParentRoute: () => AppRoute,
} )
const AppMrdRoute = AppMrdRouteImport.update({
  id: '/mrd',
  path: '/mrd',
  getParentRoute: () => AppRoute,
} )
const AppRadiologyLabRoute = AppRadiologyLabRouteImport.update({
  id: '/radiology-lab',
  path: '/radiology-lab',
  getParentRoute: () => AppRoute,
} )
const AppPathologyLabRoute = AppPathologyLabRouteImport.update({
  id: '/pathology-lab',
  path: '/pathology-lab',
  getParentRoute: () => AppRoute,
} )
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} )
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} )
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} )
const AppAdministrationRoute = AppAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => AppRoute,
} )
const AppOpdPatientRegistrationRoute =
  AppOpdPatientRegistrationRouteImport.update({
    id: '/opd/patient-registration',
    path: '/opd/patient-registration',
    getParentRoute: () => AppRoute,
  } )
const AppOpdPatientQueueRoute = AppOpdPatientQueueRouteImport.update({
  id: '/opd/patient-queue',
  path: '/opd/patient-queue',
  getParentRoute: () => AppRoute,
} )
const AppOpdMedicalRecordRoute = AppOpdMedicalRecordRouteImport.update({
  id: '/opd/medical-record',
  path: '/opd/medical-record',
  getParentRoute: () => AppRoute,
} )
const AppOpdBillSettlementRoute = AppOpdBillSettlementRouteImport.update({
  id: '/opd/bill-settlement',
  path: '/opd/bill-settlement',
  getParentRoute: () => AppRoute,
} )
const AppOpdBillRefundRoute = AppOpdBillRefundRouteImport.update({
  id: '/opd/bill-refund',
  path: '/opd/bill-refund',
  getParentRoute: () => AppRoute,
} )
const AppOpdBillListRoute = AppOpdBillListRouteImport.update({
  id: '/opd/bill-list',
  path: '/opd/bill-list',
  getParentRoute: () => AppRoute,
} )
const AppOpdBillConcessionRoute = AppOpdBillConcessionRouteImport.update({
  id: '/opd/bill-concession',
  path: '/opd/bill-concession',
  getParentRoute: () => AppRoute,
} )
const AppOpdBillRoute = AppOpdBillRouteImport.update({
  id: '/opd/bill',
  path: '/opd/bill',
  getParentRoute: () => AppRoute,
} )
const AppOpdAppointmentsRoute = AppOpdAppointmentsRouteImport.update({
  id: '/opd/appointments',
  path: '/opd/appointments',
  getParentRoute: () => AppRoute,
} )
const AppIpdTokenDisplayRoute = AppIpdTokenDisplayRouteImport.update({
  id: '/ipd/token-display',
  path: '/ipd/token-display',
  getParentRoute: () => AppRoute,
} )
const AppIpdEreRoute = AppIpdEreRouteImport.update({
  id: '/ipd/ere',
  path: '/ipd/ere',
  getParentRoute: () => AppRoute,
} )
const AppIpdChargeRoute = AppIpdChargeRouteImport.update({
  id: '/ipd/charge',
  path: '/ipd/charge',
  getParentRoute: () => AppRoute,
} )
const AppIpdAdmissionListRoute = AppIpdAdmissionListRouteImport.update({
  id: '/ipd/admission-list',
  path: '/ipd/admission-list',
  getParentRoute: () => AppRoute,
} )
const AppIpdAdmissionRoute = AppIpdAdmissionRouteImport.update({
  id: '/ipd/admission',
  path: '/ipd/admission',
  getParentRoute: () => AppRoute,
} )
const AppIpdWardPrivateRoute = AppIpdWardPrivateRouteImport.update({
  id: '/ipd/ward/private',
  path: '/ipd/ward/private',
  getParentRoute: () => AppRoute,
} )
const AppIpdWardIcuRoute = AppIpdWardIcuRouteImport.update({
  id: '/ipd/ward/icu',
  path: '/ipd/ward/icu',
  getParentRoute: () => AppRoute,
} )
const AppIpdWardGeneralRoute = AppIpdWardGeneralRouteImport.update({
  id: '/ipd/ward/general',
  path: '/ipd/ward/general',
  getParentRoute: () => AppRoute,
} )














































































































































































































































































































































































































































const AppRouteChildren = {
  AppAdministrationRoute: AppAdministrationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppMrdRoute: AppMrdRoute,
  AppNabhRoute: AppNabhRoute,
  AppNursingRoute: AppNursingRoute,
  AppOtRoute: AppOtRoute,
  AppPathologyLabRoute: AppPathologyLabRoute,
  AppRadiologyLabRoute: AppRadiologyLabRoute,
  AppTallyRoute: AppTallyRoute,
  AppIpdAdmissionRoute: AppIpdAdmissionRoute,
  AppIpdAdmissionListRoute: AppIpdAdmissionListRoute,
  AppIpdChargeRoute: AppIpdChargeRoute,
  AppIpdEreRoute: AppIpdEreRoute,
  AppIpdTokenDisplayRoute: AppIpdTokenDisplayRoute,
  AppOpdAppointmentsRoute: AppOpdAppointmentsRoute,
  AppOpdBillRoute: AppOpdBillRoute,
  AppOpdBillConcessionRoute: AppOpdBillConcessionRoute,
  AppOpdBillListRoute: AppOpdBillListRoute,
  AppOpdBillRefundRoute: AppOpdBillRefundRoute,
  AppOpdBillSettlementRoute: AppOpdBillSettlementRoute,
  AppOpdMedicalRecordRoute: AppOpdMedicalRecordRoute,
  AppOpdPatientQueueRoute: AppOpdPatientQueueRoute,
  AppOpdPatientRegistrationRoute: AppOpdPatientRegistrationRoute,
  AppIpdWardGeneralRoute: AppIpdWardGeneralRoute,
  AppIpdWardIcuRoute: AppIpdWardIcuRoute,
  AppIpdWardPrivateRoute: AppIpdWardPrivateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()









